lavalink:
    plugins:
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.6.0
          snapshot: true
          repository: https://maven.lavalink.dev/releases
        - dependency: dev.lavalink.youtube:youtube-plugin:1.13.0
          snapshot: false
        - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
          repository: https://maven.lavalink.dev/releases
          snapshot: true
        - dependency: com.github.topi314.lavalyrics:lavalyrics-plugin:2b92217
          repository: https://maven.lavalink.dev/snapshots
          snapshot: true
        - dependency: com.github.topi314.sponsorblock:sponsorblock-plugin:c1de27e
          repository: https://maven.lavalink.dev/snapshots
          snapshot: true
    server:
        bufferDurationMs: 1400
        frameBufferDurationMs: 5000
        gc-warnings: true
        opusEncodingQuality: 1
        password: your password
        playerUpdateInterval: 1
        resamplingQuality: LOW
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            mixer: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubeConfig:
            email: your email
            password: your password
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: false
logging:
    file:
        path: ./logs/
    level:
        com.github.topi314.lavasrc: INFO
        lavalink: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    lavalyrics:
        sources:
            - spotify
            - youtube
            - deezer
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            mediaAPIToken: your token
            playlistLoadLimit: 6
        deezer:
            arl: your arl cookie
            formats:
                - MP3_128
                - MP3_64
            masterDecryptionKey: g4el58wc0zvf9na1
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: default voice
        lyrics-sources:
            deezer: true
            spotify: true
            youtube: false
        providers:
            - dzisrc:"%ISRC%"
            - dzsearch:%QUERY%
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
            - scsearch:%QUERY%
            - spsearch:%QUERY%
        sources:
            applemusic: false
            deezer: true
            flowerytts: false
            spotify: true
            yandexmusic: false
            youtube: true
        spotify:
            albumLoadLimit: 10
            countryCode: US
            playlistLoadLimit: 10
            spDc: your spDc cookie
        yandexmusic:
            accessToken: your access token
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clientOptions:
            MUSIC:
                playback: false
                playlistLoading: false
                searching: true
                videoLoading: false
            MWEB:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            TV:
                playback: true
                playlistLoading: true
                searching: false
                videoLoading: true
            TVHTML5EMBEDDED:
                playback: true
                playlistLoading: false
                searching: false
                videoLoading: true
            WEB:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            WEBEMBEDDED:
                playback: true
                playlistLoading: true
                searching: false
                videoLoading: true
        clients:
            - TV
            - TVHTML5EMBEDDED
            - MUSIC
            - MWEB
            - WEBEMBEDDED
        enabled: true
        oauth:
            enabled: true
            refreshToken: your refreshToken #To get the refreshToken you must comment out the "refreshToken" line and then go to the link that it gives you in the console and do what it asks you, after logging in the refreshToken will appear in the console.
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    port: 2333
